# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.xbox_response import XboxResponse
from .raw_client import AsyncRawXboxClient, RawXboxClient


class XboxClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawXboxClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawXboxClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawXboxClient
        """
        return self._raw_client

    def profile(self, *, username: str, request_options: typing.Optional[RequestOptions] = None) -> XboxResponse:
        """
        Look up a Xbox account by its username and get the public profile.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Missing username parameter`: No `username` given.

        Docs: https://docs.osintcat.net/api-reference/endpoint/xbox

        Parameters
        ----------
        username : str
            The Xbox username.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        XboxResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.xbox.profile(
            username="Major Nelson",
        )
        """
        _response = self._raw_client.profile(username=username, request_options=request_options)
        return _response.data


class AsyncXboxClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawXboxClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawXboxClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawXboxClient
        """
        return self._raw_client

    async def profile(self, *, username: str, request_options: typing.Optional[RequestOptions] = None) -> XboxResponse:
        """
        Look up a Xbox account by its username and get the public profile.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Missing username parameter`: No `username` given.

        Docs: https://docs.osintcat.net/api-reference/endpoint/xbox

        Parameters
        ----------
        username : str
            The Xbox username.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        XboxResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.xbox.profile(
                username="Major Nelson",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.profile(username=username, request_options=request_options)
        return _response.data
