# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.tiktok_resolver_response import TiktokResolverResponse
from .raw_client import AsyncRawTiktokClient, RawTiktokClient


class TiktokClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTiktokClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTiktokClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTiktokClient
        """
        return self._raw_client

    def resolve_share_link(
        self, *, link: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TiktokResolverResponse:
        """
        Resolves a TikTok share link (e.g. `https://vm.tiktok.com/...`) to the account that shared it, with share details and the video.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Provide a valid TikTok short link via ?link=...`: No link, or not a TikTok link.
        - 404 `No user found for this link`: The link carries no sharer.
        - 502 `Could not resolve link`: The link could not be resolved right now.

        Docs: https://docs.osintcat.net/api-reference/endpoint/tiktok-resolver

        Parameters
        ----------
        link : str
            A TikTok share link. `url` or `query` are accepted as well.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TiktokResolverResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.tiktok.resolve_share_link(
            link="https://vm.tiktok.com/ZMexample/",
        )
        """
        _response = self._raw_client.resolve_share_link(link=link, request_options=request_options)
        return _response.data


class AsyncTiktokClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTiktokClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTiktokClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTiktokClient
        """
        return self._raw_client

    async def resolve_share_link(
        self, *, link: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TiktokResolverResponse:
        """
        Resolves a TikTok share link (e.g. `https://vm.tiktok.com/...`) to the account that shared it, with share details and the video.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Provide a valid TikTok short link via ?link=...`: No link, or not a TikTok link.
        - 404 `No user found for this link`: The link carries no sharer.
        - 502 `Could not resolve link`: The link could not be resolved right now.

        Docs: https://docs.osintcat.net/api-reference/endpoint/tiktok-resolver

        Parameters
        ----------
        link : str
            A TikTok share link. `url` or `query` are accepted as well.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TiktokResolverResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tiktok.resolve_share_link(
                link="https://vm.tiktok.com/ZMexample/",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resolve_share_link(link=link, request_options=request_options)
        return _response.data
