# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.email_osint_response import EmailOsintResponse
from .raw_client import AsyncRawEmailClient, RawEmailClient


class EmailClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEmailClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEmailClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEmailClient
        """
        return self._raw_client

    def lookup(
        self, *, query: str, purpose: str, request_options: typing.Optional[RequestOptions] = None
    ) -> EmailOsintResponse:
        """
        Checks which websites and services an e-mail address is registered with and in which breaches it appears. Every request must state its purpose.

        A request without a purpose (parameter `purpose`, header `X-Purpose`, or `Purpose: ...` at the end of your User-Agent) is refused with `400 USER_AGENT_IDENTITY_REQUIRED`.

        Does not use your daily allowance. Each lookup that finds something is charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing, or fails, is not charged.

        Errors:
        - 400 `USER_AGENT_IDENTITY_REQUIRED`: No purpose given.
        - 401 `API key required`: No `X-API-KEY` header.
        - 402 `INSUFFICIENT_BALANCE`: Your balance does not cover the lookup.
        - 424 `Provider Error`: The lookup could not be completed. Not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/email-osint

        Parameters
        ----------
        query : str
            The e-mail address (`email` is accepted as well).

        purpose : str
            Why you run the lookup, e.g. `fraud prevention`. Required unless sent as a header (below).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmailOsintResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.email.lookup(
            query="user@example.com",
            purpose="fraud prevention",
        )
        """
        _response = self._raw_client.lookup(query=query, purpose=purpose, request_options=request_options)
        return _response.data


class AsyncEmailClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEmailClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEmailClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEmailClient
        """
        return self._raw_client

    async def lookup(
        self, *, query: str, purpose: str, request_options: typing.Optional[RequestOptions] = None
    ) -> EmailOsintResponse:
        """
        Checks which websites and services an e-mail address is registered with and in which breaches it appears. Every request must state its purpose.

        A request without a purpose (parameter `purpose`, header `X-Purpose`, or `Purpose: ...` at the end of your User-Agent) is refused with `400 USER_AGENT_IDENTITY_REQUIRED`.

        Does not use your daily allowance. Each lookup that finds something is charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing, or fails, is not charged.

        Errors:
        - 400 `USER_AGENT_IDENTITY_REQUIRED`: No purpose given.
        - 401 `API key required`: No `X-API-KEY` header.
        - 402 `INSUFFICIENT_BALANCE`: Your balance does not cover the lookup.
        - 424 `Provider Error`: The lookup could not be completed. Not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/email-osint

        Parameters
        ----------
        query : str
            The e-mail address (`email` is accepted as well).

        purpose : str
            Why you run the lookup, e.g. `fraud prevention`. Required unless sent as a header (below).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmailOsintResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.email.lookup(
                query="user@example.com",
                purpose="fraud prevention",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.lookup(query=query, purpose=purpose, request_options=request_options)
        return _response.data
