# This file was auto-generated by Fern from our API Definition.

import typing

QueryVinRequestType = typing.Union[
    typing.Literal["decode", "batch", "wmi", "makes", "manufacturers", "variables", "canadian"], typing.Any
]
