# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.minecraft_osint_response import MinecraftOsintResponse
from ..types.minecraft_profile_response import MinecraftProfileResponse
from ..types.minecraft_response import MinecraftResponse
from .raw_client import AsyncRawMinecraftClient, RawMinecraftClient
from .types.leaks_minecraft_request_type import LeaksMinecraftRequestType
from .types.player_minecraft_request_type import PlayerMinecraftRequestType


class MinecraftClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMinecraftClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMinecraftClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMinecraftClient
        """
        return self._raw_client

    def player(
        self,
        *,
        query: str,
        query_type: typing.Optional[PlayerMinecraftRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MinecraftResponse:
        """
        Combines the Minecraft profile of a player (UUID, name history, capes, skins) with records about them found in Minecraft server leaks.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/minecraft

        Parameters
        ----------
        query : str
            A Minecraft username (or the value matching `type`).

        query_type : typing.Optional[PlayerMinecraftRequestType]
            What `query` is for the leak search: `username` (default), `uuid`, `email` or `ip`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MinecraftResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.minecraft.player(
            query="Notch",
        )
        """
        _response = self._raw_client.player(query=query, query_type=query_type, request_options=request_options)
        return _response.data

    def leaks(
        self,
        *,
        query: str,
        query_type: LeaksMinecraftRequestType,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MinecraftOsintResponse:
        """
        Searches Minecraft server leaks for one value. Use [Minecraft Player](https://docs.osintcat.net/api-reference/endpoint/minecraft) for a profile plus leaks in one call.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `invalid query type`: `type` is missing or not one of the allowed values; `allowed_types` lists them.
        - 424 `Upstream returned an empty response`: The search could not be completed; the response carries an `error_id`.

        Docs: https://docs.osintcat.net/api-reference/endpoint/minecraft-osint

        Parameters
        ----------
        query : str
            The value to search for.

        query_type : LeaksMinecraftRequestType
            One of `username`, `uuid`, `email`, `ip`, `password`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MinecraftOsintResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.minecraft.leaks(
            query="Notch",
            query_type="username",
        )
        """
        _response = self._raw_client.leaks(query=query, query_type=query_type, request_options=request_options)
        return _response.data

    def profile(
        self, *, username: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MinecraftProfileResponse:
        """
        Look up a Minecraft account by its username and get the public profile.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Missing username parameter`: No `username` given.

        Docs: https://docs.osintcat.net/api-reference/endpoint/minecraft-profile

        Parameters
        ----------
        username : str
            The Minecraft username.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MinecraftProfileResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.minecraft.profile(
            username="Notch",
        )
        """
        _response = self._raw_client.profile(username=username, request_options=request_options)
        return _response.data


class AsyncMinecraftClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMinecraftClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMinecraftClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMinecraftClient
        """
        return self._raw_client

    async def player(
        self,
        *,
        query: str,
        query_type: typing.Optional[PlayerMinecraftRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MinecraftResponse:
        """
        Combines the Minecraft profile of a player (UUID, name history, capes, skins) with records about them found in Minecraft server leaks.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/minecraft

        Parameters
        ----------
        query : str
            A Minecraft username (or the value matching `type`).

        query_type : typing.Optional[PlayerMinecraftRequestType]
            What `query` is for the leak search: `username` (default), `uuid`, `email` or `ip`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MinecraftResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.minecraft.player(
                query="Notch",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.player(query=query, query_type=query_type, request_options=request_options)
        return _response.data

    async def leaks(
        self,
        *,
        query: str,
        query_type: LeaksMinecraftRequestType,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MinecraftOsintResponse:
        """
        Searches Minecraft server leaks for one value. Use [Minecraft Player](https://docs.osintcat.net/api-reference/endpoint/minecraft) for a profile plus leaks in one call.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `invalid query type`: `type` is missing or not one of the allowed values; `allowed_types` lists them.
        - 424 `Upstream returned an empty response`: The search could not be completed; the response carries an `error_id`.

        Docs: https://docs.osintcat.net/api-reference/endpoint/minecraft-osint

        Parameters
        ----------
        query : str
            The value to search for.

        query_type : LeaksMinecraftRequestType
            One of `username`, `uuid`, `email`, `ip`, `password`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MinecraftOsintResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.minecraft.leaks(
                query="Notch",
                query_type="username",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.leaks(query=query, query_type=query_type, request_options=request_options)
        return _response.data

    async def profile(
        self, *, username: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MinecraftProfileResponse:
        """
        Look up a Minecraft account by its username and get the public profile.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Missing username parameter`: No `username` given.

        Docs: https://docs.osintcat.net/api-reference/endpoint/minecraft-profile

        Parameters
        ----------
        username : str
            The Minecraft username.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MinecraftProfileResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.minecraft.profile(
                username="Notch",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.profile(username=username, request_options=request_options)
        return _response.data
