# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.phone_osint_response import PhoneOsintResponse
from .raw_client import AsyncRawPhoneClient, RawPhoneClient


class PhoneClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPhoneClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPhoneClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPhoneClient
        """
        return self._raw_client

    def lookup(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> PhoneOsintResponse:
        """
        Returns what is known about a phone number: whether it is valid, the carrier and line type, the country, linked online accounts and a risk score.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `phone_*`: The number cannot be a valid phone number; `code` says why (e.g. `phone_too_short`).
        - 424 `Upstream provider error`: The lookup could not be completed.
        - 424 `The request timed out.`: The lookup took too long.

        Docs: https://docs.osintcat.net/api-reference/endpoint/phone-osint

        Parameters
        ----------
        query : str
            The phone number in international format, e.g. `+4915112345678`. Spaces and dashes are allowed.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneOsintResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.phone.lookup(
            query="+4915112345678",
        )
        """
        _response = self._raw_client.lookup(query=query, request_options=request_options)
        return _response.data


class AsyncPhoneClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPhoneClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPhoneClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPhoneClient
        """
        return self._raw_client

    async def lookup(
        self, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneOsintResponse:
        """
        Returns what is known about a phone number: whether it is valid, the carrier and line type, the country, linked online accounts and a risk score.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `phone_*`: The number cannot be a valid phone number; `code` says why (e.g. `phone_too_short`).
        - 424 `Upstream provider error`: The lookup could not be completed.
        - 424 `The request timed out.`: The lookup took too long.

        Docs: https://docs.osintcat.net/api-reference/endpoint/phone-osint

        Parameters
        ----------
        query : str
            The phone number in international format, e.g. `+4915112345678`. Spaces and dashes are allowed.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneOsintResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phone.lookup(
                query="+4915112345678",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.lookup(query=query, request_options=request_options)
        return _response.data
