# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chilean_car_response import ChileanCarResponse
from ..types.chilean_name_response import ChileanNameResponse
from .raw_client import AsyncRawChileClient, RawChileClient


class ChileClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChileClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChileClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChileClient
        """
        return self._raw_client

    def person(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> ChileanNameResponse:
        """
        Searches Chilean public records for people by name.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests are refused with `429 LIMIT_REACHED` until it resets at 00:00 UTC.

        Docs: https://docs.osintcat.net/api-reference/endpoint/chilean-name

        Parameters
        ----------
        query : str
            A full or partial name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChileanNameResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.chile.person(
            query="Juan Perez",
        )
        """
        _response = self._raw_client.person(query=query, request_options=request_options)
        return _response.data

    def vehicle(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> ChileanCarResponse:
        """
        Searches Chilean vehicle records by licence plate.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests are refused with `429 LIMIT_REACHED` until it resets at 00:00 UTC.

        Docs: https://docs.osintcat.net/api-reference/endpoint/chilean-car

        Parameters
        ----------
        query : str
            The licence plate.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChileanCarResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.chile.vehicle(
            query="ABCD12",
        )
        """
        _response = self._raw_client.vehicle(query=query, request_options=request_options)
        return _response.data


class AsyncChileClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChileClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChileClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChileClient
        """
        return self._raw_client

    async def person(
        self, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ChileanNameResponse:
        """
        Searches Chilean public records for people by name.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests are refused with `429 LIMIT_REACHED` until it resets at 00:00 UTC.

        Docs: https://docs.osintcat.net/api-reference/endpoint/chilean-name

        Parameters
        ----------
        query : str
            A full or partial name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChileanNameResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chile.person(
                query="Juan Perez",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.person(query=query, request_options=request_options)
        return _response.data

    async def vehicle(
        self, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ChileanCarResponse:
        """
        Searches Chilean vehicle records by licence plate.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests are refused with `429 LIMIT_REACHED` until it resets at 00:00 UTC.

        Docs: https://docs.osintcat.net/api-reference/endpoint/chilean-car

        Parameters
        ----------
        query : str
            The licence plate.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChileanCarResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chile.vehicle(
                query="ABCD12",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.vehicle(query=query, request_options=request_options)
        return _response.data
