# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_response import GithubResponse
from .raw_client import AsyncRawGithubClient, RawGithubClient


class GithubClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawGithubClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawGithubClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawGithubClient
        """
        return self._raw_client

    def profile(self, *, username: str, request_options: typing.Optional[RequestOptions] = None) -> GithubResponse:
        """
        Look up a GitHub account by its username and get the public profile.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Missing username parameter`: No `username` given.

        Docs: https://docs.osintcat.net/api-reference/endpoint/github

        Parameters
        ----------
        username : str
            The GitHub username.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.github.profile(
            username="octocat",
        )
        """
        _response = self._raw_client.profile(username=username, request_options=request_options)
        return _response.data


class AsyncGithubClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawGithubClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawGithubClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawGithubClient
        """
        return self._raw_client

    async def profile(
        self, *, username: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubResponse:
        """
        Look up a GitHub account by its username and get the public profile.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Missing username parameter`: No `username` given.

        Docs: https://docs.osintcat.net/api-reference/endpoint/github

        Parameters
        ----------
        username : str
            The GitHub username.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.github.profile(
                username="octocat",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.profile(username=username, request_options=request_options)
        return _response.data
