# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.machine_file_response import MachineFileResponse
from ..types.machine_files_response import MachineFilesResponse
from ..types.machine_info_response import MachineInfoResponse
from ..types.machine_search_response import MachineSearchResponse
from ..types.machine_viewer_stats import MachineViewerStats
from .raw_client import AsyncRawMachineViewerClient, RawMachineViewerClient


class MachineViewerClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMachineViewerClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMachineViewerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMachineViewerClient
        """
        return self._raw_client

    def stats(self, *, request_options: typing.Optional[RequestOptions] = None) -> MachineViewerStats:
        """
        How many machines, files, passwords, tokens, cookies and payment cards the Machine Viewer holds.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MachineViewerStats
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.machine_viewer.stats()
        """
        _response = self._raw_client.stats(request_options=request_options)
        return _response.data

    def search(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> MachineSearchResponse:
        """
        Searches machines by name, username, hostname or machine ID.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        query : str
            What to search for: a name, username, hostname or machine ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MachineSearchResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.machine_viewer.search(
            query="DESKTOP",
        )
        """
        _response = self._raw_client.search(query=query, request_options=request_options)
        return _response.data

    def machine(
        self, machine_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MachineInfoResponse:
        """
        One machine, with the e-mail addresses and tokens found on it.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        machine_id : str
            Machine ID (a UUID), from `machineViewer.search`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MachineInfoResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.machine_viewer.machine(
            machine_id="742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5",
        )
        """
        _response = self._raw_client.machine(machine_id, request_options=request_options)
        return _response.data

    def files(
        self, machine_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MachineFilesResponse:
        """
        Every file of a machine, with its path and size. Use a file's `id` with `machineViewer.file`.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        machine_id : str
            Machine ID (a UUID), from `machineViewer.search`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MachineFilesResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.machine_viewer.files(
            machine_id="742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5",
        )
        """
        _response = self._raw_client.files(machine_id, request_options=request_options)
        return _response.data

    def file(self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> MachineFileResponse:
        """
        One file, with its content as text.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        file_id : str
            File ID, from `machineViewer.files`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MachineFileResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.machine_viewer.file(
            file_id="aB3dE5fG7hI9jK1lM3nO",
        )
        """
        _response = self._raw_client.file(file_id, request_options=request_options)
        return _response.data

    def download_file(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        The file itself, as it was in the log.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        file_id : str
            File ID, from `machineViewer.files`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.machine_viewer.download_file(
            file_id="file_id",
        )
        """
        with self._raw_client.download_file(file_id, request_options=request_options) as r:
            yield from r.data

    def download_machine(
        self, machine_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Every file of a machine in one ZIP archive.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        machine_id : str
            Machine ID (a UUID), from `machineViewer.search`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.machine_viewer.download_machine(
            machine_id="machine_id",
        )
        """
        with self._raw_client.download_machine(machine_id, request_options=request_options) as r:
            yield from r.data


class AsyncMachineViewerClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMachineViewerClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMachineViewerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMachineViewerClient
        """
        return self._raw_client

    async def stats(self, *, request_options: typing.Optional[RequestOptions] = None) -> MachineViewerStats:
        """
        How many machines, files, passwords, tokens, cookies and payment cards the Machine Viewer holds.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MachineViewerStats
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.machine_viewer.stats()


        asyncio.run(main())
        """
        _response = await self._raw_client.stats(request_options=request_options)
        return _response.data

    async def search(
        self, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MachineSearchResponse:
        """
        Searches machines by name, username, hostname or machine ID.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        query : str
            What to search for: a name, username, hostname or machine ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MachineSearchResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.machine_viewer.search(
                query="DESKTOP",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search(query=query, request_options=request_options)
        return _response.data

    async def machine(
        self, machine_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MachineInfoResponse:
        """
        One machine, with the e-mail addresses and tokens found on it.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        machine_id : str
            Machine ID (a UUID), from `machineViewer.search`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MachineInfoResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.machine_viewer.machine(
                machine_id="742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.machine(machine_id, request_options=request_options)
        return _response.data

    async def files(
        self, machine_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MachineFilesResponse:
        """
        Every file of a machine, with its path and size. Use a file's `id` with `machineViewer.file`.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        machine_id : str
            Machine ID (a UUID), from `machineViewer.search`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MachineFilesResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.machine_viewer.files(
                machine_id="742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.files(machine_id, request_options=request_options)
        return _response.data

    async def file(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MachineFileResponse:
        """
        One file, with its content as text.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        file_id : str
            File ID, from `machineViewer.files`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MachineFileResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.machine_viewer.file(
                file_id="aB3dE5fG7hI9jK1lM3nO",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.file(file_id, request_options=request_options)
        return _response.data

    async def download_file(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        The file itself, as it was in the log.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        file_id : str
            File ID, from `machineViewer.files`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.machine_viewer.download_file(
                file_id="file_id",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_file(file_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def download_machine(
        self, machine_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Every file of a machine in one ZIP archive.

        Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer

        Parameters
        ----------
        machine_id : str
            Machine ID (a UUID), from `machineViewer.search`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.machine_viewer.download_machine(
                machine_id="machine_id",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_machine(machine_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk
