# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.instagram_resolver_response import InstagramResolverResponse
from .raw_client import AsyncRawInstagramClient, RawInstagramClient


class InstagramClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInstagramClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInstagramClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInstagramClient
        """
        return self._raw_client

    def resolve_share_link(
        self, *, link: str, request_options: typing.Optional[RequestOptions] = None
    ) -> InstagramResolverResponse:
        """
        Resolves an Instagram post or reel share link to the account that shared it and the author of the post. Profile links cannot be resolved.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Provide a valid Instagram URL via ?link=...`: No link, not an Instagram link, or the link expired or points to a private post. Not charged.
        - 422 `profile_link`: A profile link: only post and reel share links can be resolved. Not charged.
        - 424 `(message)`: The link could not be resolved right now. Not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/instagram-resolver

        Parameters
        ----------
        link : str
            An Instagram post or reel share link (with its `igsh` parameter). `url` or `query` are accepted as well.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InstagramResolverResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.instagram.resolve_share_link(
            link="https://www.instagram.com/reel/Cexample/?igsh=MWexample",
        )
        """
        _response = self._raw_client.resolve_share_link(link=link, request_options=request_options)
        return _response.data


class AsyncInstagramClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInstagramClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInstagramClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInstagramClient
        """
        return self._raw_client

    async def resolve_share_link(
        self, *, link: str, request_options: typing.Optional[RequestOptions] = None
    ) -> InstagramResolverResponse:
        """
        Resolves an Instagram post or reel share link to the account that shared it and the author of the post. Profile links cannot be resolved.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Provide a valid Instagram URL via ?link=...`: No link, not an Instagram link, or the link expired or points to a private post. Not charged.
        - 422 `profile_link`: A profile link: only post and reel share links can be resolved. Not charged.
        - 424 `(message)`: The link could not be resolved right now. Not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/instagram-resolver

        Parameters
        ----------
        link : str
            An Instagram post or reel share link (with its `igsh` parameter). `url` or `query` are accepted as well.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InstagramResolverResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.instagram.resolve_share_link(
                link="https://www.instagram.com/reel/Cexample/?igsh=MWexample",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resolve_share_link(link=link, request_options=request_options)
        return _response.data
