# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .breach_response import BreachResponse
    from .chess_response import ChessResponse
    from .chilean_car_response import ChileanCarResponse
    from .chilean_name_response import ChileanNameResponse
    from .database_search_response import DatabaseSearchResponse
    from .dns_resolver_response import DnsResolverResponse
    from .domain_response import DomainResponse
    from .email_osint_response import EmailOsintResponse
    from .email_osint_results import EmailOsintResults
    from .error import Error
    from .github_extra_data import GithubExtraData
    from .github_response import GithubResponse
    from .instagram_resolver_response import InstagramResolverResponse
    from .ip_response import IpResponse
    from .minecraft_osint_response import MinecraftOsintResponse
    from .minecraft_profile_extra_data import MinecraftProfileExtraData
    from .minecraft_profile_response import MinecraftProfileResponse
    from .minecraft_response import MinecraftResponse
    from .modules_modules import ModulesModules
    from .modules_response import ModulesResponse
    from .modules_user import ModulesUser
    from .phone_osint_response import PhoneOsintResponse
    from .phone_osint_risk import PhoneOsintRisk
    from .reddit_extra_data import RedditExtraData
    from .reddit_response import RedditResponse
    from .steam_extra_data import SteamExtraData
    from .steam_response import SteamResponse
    from .tiktok_resolver_response import TiktokResolverResponse
    from .twitch_extra_data import TwitchExtraData
    from .twitch_response import TwitchResponse
    from .twitter_profile import TwitterProfile
    from .twitter_response import TwitterResponse
    from .usage_meta import UsageMeta
    from .usage_meta_lookups_left import UsageMetaLookupsLeft
    from .user_account_info import UserAccountInfo
    from .user_response import UserResponse
    from .user_usage import UserUsage
    from .vin_response import VinResponse
    from .xbox_extra_data import XboxExtraData
    from .xbox_response import XboxResponse
_dynamic_imports: typing.Dict[str, str] = {
    "BreachResponse": ".breach_response",
    "ChessResponse": ".chess_response",
    "ChileanCarResponse": ".chilean_car_response",
    "ChileanNameResponse": ".chilean_name_response",
    "DatabaseSearchResponse": ".database_search_response",
    "DnsResolverResponse": ".dns_resolver_response",
    "DomainResponse": ".domain_response",
    "EmailOsintResponse": ".email_osint_response",
    "EmailOsintResults": ".email_osint_results",
    "Error": ".error",
    "GithubExtraData": ".github_extra_data",
    "GithubResponse": ".github_response",
    "InstagramResolverResponse": ".instagram_resolver_response",
    "IpResponse": ".ip_response",
    "MinecraftOsintResponse": ".minecraft_osint_response",
    "MinecraftProfileExtraData": ".minecraft_profile_extra_data",
    "MinecraftProfileResponse": ".minecraft_profile_response",
    "MinecraftResponse": ".minecraft_response",
    "ModulesModules": ".modules_modules",
    "ModulesResponse": ".modules_response",
    "ModulesUser": ".modules_user",
    "PhoneOsintResponse": ".phone_osint_response",
    "PhoneOsintRisk": ".phone_osint_risk",
    "RedditExtraData": ".reddit_extra_data",
    "RedditResponse": ".reddit_response",
    "SteamExtraData": ".steam_extra_data",
    "SteamResponse": ".steam_response",
    "TiktokResolverResponse": ".tiktok_resolver_response",
    "TwitchExtraData": ".twitch_extra_data",
    "TwitchResponse": ".twitch_response",
    "TwitterProfile": ".twitter_profile",
    "TwitterResponse": ".twitter_response",
    "UsageMeta": ".usage_meta",
    "UsageMetaLookupsLeft": ".usage_meta_lookups_left",
    "UserAccountInfo": ".user_account_info",
    "UserResponse": ".user_response",
    "UserUsage": ".user_usage",
    "VinResponse": ".vin_response",
    "XboxExtraData": ".xbox_extra_data",
    "XboxResponse": ".xbox_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BreachResponse",
    "ChessResponse",
    "ChileanCarResponse",
    "ChileanNameResponse",
    "DatabaseSearchResponse",
    "DnsResolverResponse",
    "DomainResponse",
    "EmailOsintResponse",
    "EmailOsintResults",
    "Error",
    "GithubExtraData",
    "GithubResponse",
    "InstagramResolverResponse",
    "IpResponse",
    "MinecraftOsintResponse",
    "MinecraftProfileExtraData",
    "MinecraftProfileResponse",
    "MinecraftResponse",
    "ModulesModules",
    "ModulesResponse",
    "ModulesUser",
    "PhoneOsintResponse",
    "PhoneOsintRisk",
    "RedditExtraData",
    "RedditResponse",
    "SteamExtraData",
    "SteamResponse",
    "TiktokResolverResponse",
    "TwitchExtraData",
    "TwitchResponse",
    "TwitterProfile",
    "TwitterResponse",
    "UsageMeta",
    "UsageMetaLookupsLeft",
    "UserAccountInfo",
    "UserResponse",
    "UserUsage",
    "VinResponse",
    "XboxExtraData",
    "XboxResponse",
]
