# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .usage_meta import UsageMeta


class BreachResponse(UncheckedBaseModel):
    api: typing.Optional[str] = pydantic.Field(default=None)
    """
    Always `OsintCat`.
    """

    elapsed_ms: typing.Optional[float] = pydantic.Field(default=None)
    """
    Time the search took, in milliseconds.
    """

    timestamp: typing.Optional[str] = pydantic.Field(default=None)
    """
    When the search ran (UTC), e.g. `Oct 6th 09:41`.
    """

    results_count: typing.Optional[float] = pydantic.Field(default=None)
    """
    Number of records in `breach_data`.
    """

    breach_data: typing.Optional[typing.List[typing.Any]] = pydantic.Field(default=None)
    """
    Matching records. The fields of a record depend on the breach it comes from (for example `email`, `username`, `password`, `hash`, `ip`, `name`, `phone`); `source_db` names the breach or index the record was found in.
    """

    meta: typing_extensions.Annotated[
        typing.Optional[UsageMeta], FieldMetadata(alias="_meta"), pydantic.Field(alias="_meta")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
