# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ChessResponse(UncheckedBaseModel):
    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    `true` when the lookup ran.
    """

    found: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether anything was found.
    """

    query: typing.Optional[str] = pydantic.Field(default=None)
    """
    The query.
    """

    resolved_username: typing.Optional[str] = pydantic.Field(default=None)
    """
    The username the lookup settled on.
    """

    live_profile: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The public profile (name, country, joined, last online, followers ...), or `null`.
    """

    live_stats: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Ratings: `rapid`, `blitz`, `bullet`, `fide` (each `null` when unrated).
    """

    live_clubs: typing.Optional[typing.List[typing.Any]] = pydantic.Field(default=None)
    """
    Up to 10 clubs.
    """

    leak_records: typing.Optional[typing.List[typing.Any]] = pydantic.Field(default=None)
    """
    Records from the Chess.com leak.
    """

    leak_count: typing.Optional[float] = pydantic.Field(default=None)
    """
    Number of leak records.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
