# This file was auto-generated by Fern from our API Definition.

import typing

ChileanNameResponse = typing.Any
"""
The matching people (RUT, full name and the public record details available for them). Results are cached for an hour.
"""
