# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class DatabaseSearchResponse(UncheckedBaseModel):
    results: typing.Optional[typing.List[typing.Any]] = pydantic.Field(default=None)
    """
    Matching entries (typically a URL, login and password, and when it was collected).
    """

    results_count: typing.Optional[float] = pydantic.Field(default=None)
    """
    Number of entries.
    """

    query: typing.Optional[str] = pydantic.Field(default=None)
    """
    The query searched for.
    """

    query_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="type"),
        pydantic.Field(alias="type", description="`email` or `domain`."),
    ] = None
    """
    `email` or `domain`.
    """

    execution_time: typing.Optional[str] = pydantic.Field(default=None)
    """
    Time the search took.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    `success`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
