# This file was auto-generated by Fern from our API Definition.

import typing

DomainResponse = typing.List[typing.Dict[str, typing.Any]]
"""
An array of breach records. The fields of a record depend on the breach it comes from.
"""
