# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .email_osint_results import EmailOsintResults
from .usage_meta import UsageMeta


class EmailOsintResponse(UncheckedBaseModel):
    """
    Results for the same address may come from a cache for up to 15 minutes.
    """

    results: typing.Optional[EmailOsintResults] = None
    meta: typing_extensions.Annotated[
        typing.Optional[UsageMeta], FieldMetadata(alias="_meta"), pydantic.Field(alias="_meta")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
