# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class Error(UncheckedBaseModel):
    """
    What every error response carries. `error` is a short code or message; some errors add more fields (`error_id`, `code`, `allowed_types`).
    """

    error: typing.Optional[str] = None
    message: typing.Optional[str] = None
    error_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Quote it to support.
    """

    code: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
