# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class GithubExtraData(UncheckedBaseModel):
    username: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="Username"), pydantic.Field(alias="Username", description="Login.")
    ] = None
    """
    Login.
    """

    name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="Name"), pydantic.Field(alias="Name", description="Name.")
    ] = None
    """
    Name.
    """

    bio: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="Bio"), pydantic.Field(alias="Bio", description="Bio.")
    ] = None
    """
    Bio.
    """

    location: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="Location"), pydantic.Field(alias="Location", description="Location.")
    ] = None
    """
    Location.
    """

    company: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="Company"), pydantic.Field(alias="Company", description="Company.")
    ] = None
    """
    Company.
    """

    blog: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="Blog"), pydantic.Field(alias="Blog", description="Website.")
    ] = None
    """
    Website.
    """

    email: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="Email"), pydantic.Field(alias="Email", description="Public e-mail.")
    ] = None
    """
    Public e-mail.
    """

    twitter: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Twitter"),
        pydantic.Field(alias="Twitter", description="X/Twitter handle."),
    ] = None
    """
    X/Twitter handle.
    """

    followers: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="Followers"),
        pydantic.Field(alias="Followers", description="Followers."),
    ] = None
    """
    Followers.
    """

    following: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="Following"),
        pydantic.Field(alias="Following", description="Following."),
    ] = None
    """
    Following.
    """

    public_repos: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="PublicRepos"),
        pydantic.Field(alias="PublicRepos", description="Public repositories."),
    ] = None
    """
    Public repositories.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="CreatedAt"),
        pydantic.Field(alias="CreatedAt", description="Account creation."),
    ] = None
    """
    Account creation.
    """

    profile_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ProfileUrl"),
        pydantic.Field(alias="ProfileUrl", description="Profile link."),
    ] = None
    """
    Profile link.
    """

    repositories: typing_extensions.Annotated[
        typing.Optional[typing.List[typing.Any]],
        FieldMetadata(alias="Repositories"),
        pydantic.Field(
            alias="Repositories",
            description="The 10 most recently pushed repositories (name, description, url, language, stars, forks).",
        ),
    ] = None
    """
    The 10 most recently pushed repositories (name, description, url, language, stars, forks).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
