# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .usage_meta import UsageMeta


class InstagramResolverResponse(UncheckedBaseModel):
    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    `true` when resolved.
    """

    author: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The account that posted it: `username`, `avatar`.
    """

    sharer: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The account that shared the link: `username`, `full_name`, `id`, `avatar`.
    """

    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the shared post.
    """

    meta: typing_extensions.Annotated[
        typing.Optional[UsageMeta], FieldMetadata(alias="_meta"), pydantic.Field(alias="_meta")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
