# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class IpResponse(UncheckedBaseModel):
    ipleaks: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Services seen on the address: open ports, banners, hostnames, known vulnerabilities. `{"error": "No information available for that IP."}` when nothing was seen.
    """

    ipinfo: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Location and network: country, region, city, coordinates, time zone, ASN and organisation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
