# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class MachineViewerStats(UncheckedBaseModel):
    total_machines: typing.Optional[int] = pydantic.Field(default=None)
    """
    Machines.
    """

    total_files: typing.Optional[int] = pydantic.Field(default=None)
    """
    Files.
    """

    total_passwords: typing.Optional[int] = pydantic.Field(default=None)
    """
    Passwords.
    """

    total_unique_passwords: typing.Optional[int] = pydantic.Field(default=None)
    """
    Distinct passwords.
    """

    total_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Tokens.
    """

    total_cookies: typing.Optional[int] = pydantic.Field(default=None)
    """
    Cookies.
    """

    total_credit_cards: typing.Optional[int] = pydantic.Field(default=None)
    """
    Payment cards.
    """

    total_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    Size of all files, in bytes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
