# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class Machine(UncheckedBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Machine ID (a UUID).
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the log the machine came from.
    """

    imported_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When it was added (ISO 8601).
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    Country code, if known.
    """

    ip: typing.Optional[str] = pydantic.Field(default=None)
    """
    IP address, if known.
    """

    file_count: typing.Optional[int] = None
    total_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    Size of all files, in bytes.
    """

    has_passwords: typing.Optional[bool] = None
    password_count: typing.Optional[int] = None
    unique_password_count: typing.Optional[int] = None
    has_tokens: typing.Optional[bool] = None
    token_count: typing.Optional[int] = None
    has_cookies: typing.Optional[bool] = None
    cookie_count: typing.Optional[int] = None
    has_credit_cards: typing.Optional[bool] = None
    credit_card_count: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
