# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class MachineFile(UncheckedBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    File ID, for the file endpoints.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    File name.
    """

    path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Path inside the log.
    """

    size: typing.Optional[int] = pydantic.Field(default=None)
    """
    Size in bytes.
    """

    file_type: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="type"), pydantic.Field(alias="type", description="Always `file`.")
    ] = None
    """
    Always `file`.
    """

    is_password_file: typing.Optional[bool] = None
    is_token_file: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
