# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .machine import Machine


class MachineInfoResponse(UncheckedBaseModel):
    success: typing.Optional[bool] = None
    machine: typing.Optional[Machine] = None
    emails: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    E-mail addresses found on the machine.
    """

    tokens: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Tokens found on the machine.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
