# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class MachineFileInfo(UncheckedBaseModel):
    id: typing.Optional[str] = None
    machine_id: typing.Optional[str] = None
    machine_name: typing.Optional[str] = None
    path: typing.Optional[str] = None
    filename: typing.Optional[str] = None
    size: typing.Optional[int] = None
    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    The file content as text.
    """

    is_password_file: typing.Optional[bool] = None
    is_token_file: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
