# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class MinecraftProfileExtraData(UncheckedBaseModel):
    username: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Username"),
        pydantic.Field(alias="Username", description="Current username."),
    ] = None
    """
    Current username.
    """

    uuid_: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="UUID"), pydantic.Field(alias="UUID", description="Minecraft UUID.")
    ] = None
    """
    Minecraft UUID.
    """

    name_history: typing_extensions.Annotated[
        typing.Optional[typing.List[typing.Any]],
        FieldMetadata(alias="NameHistory"),
        pydantic.Field(alias="NameHistory", description="Earlier usernames."),
    ] = None
    """
    Earlier usernames.
    """

    laby_username: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="LabyUsername"),
        pydantic.Field(alias="LabyUsername", description="Username shown by the LabyMod profile, if any."),
    ] = None
    """
    Username shown by the LabyMod profile, if any.
    """

    profile_pic_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ProfilePicUrl"),
        pydantic.Field(alias="ProfilePicUrl", description="Head render of the skin."),
    ] = None
    """
    Head render of the skin.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
