# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .modules_modules import ModulesModules
from .modules_user import ModulesUser


class ModulesResponse(UncheckedBaseModel):
    modules: typing.Optional[typing.List[ModulesModules]] = pydantic.Field(default=None)
    """
    One entry per module.
    """

    user: typing.Optional[ModulesUser] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
