# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .phone_osint_risk import PhoneOsintRisk
from .usage_meta import UsageMeta


class PhoneOsintResponse(UncheckedBaseModel):
    module: typing.Optional[str] = pydantic.Field(default=None)
    """
    Always `phone`.
    """

    query: typing.Optional[str] = pydantic.Field(default=None)
    """
    The number in E.164 format.
    """

    found: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether anything was found.
    """

    risk: typing.Optional[PhoneOsintRisk] = None
    summary: typing.Optional[typing.List[typing.Any]] = pydantic.Field(default=None)
    """
    The main facts as `{label, value}` pairs.
    """

    sections: typing.Optional[typing.List[typing.Any]] = pydantic.Field(default=None)
    """
    Detailed findings, grouped (carrier, location, linked accounts ...).
    """

    raw: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The full answer the summary is built from.
    """

    meta: typing_extensions.Annotated[
        typing.Optional[UsageMeta], FieldMetadata(alias="_meta"), pydantic.Field(alias="_meta")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
