# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class RedditExtraData(UncheckedBaseModel):
    username: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="Username"), pydantic.Field(alias="Username", description="Username.")
    ] = None
    """
    Username.
    """

    display_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="DisplayName"),
        pydantic.Field(alias="DisplayName", description="Display name."),
    ] = None
    """
    Display name.
    """

    comment_karma: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="CommentKarma"),
        pydantic.Field(alias="CommentKarma", description="Comment karma."),
    ] = None
    """
    Comment karma.
    """

    link_karma: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="LinkKarma"),
        pydantic.Field(alias="LinkKarma", description="Post karma."),
    ] = None
    """
    Post karma.
    """

    total_karma: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="TotalKarma"),
        pydantic.Field(alias="TotalKarma", description="Total karma."),
    ] = None
    """
    Total karma.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="CreatedAt"),
        pydantic.Field(alias="CreatedAt", description="Account creation (Unix time)."),
    ] = None
    """
    Account creation (Unix time).
    """

    is_verified: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="IsVerified"),
        pydantic.Field(alias="IsVerified", description="Verified e-mail."),
    ] = None
    """
    Verified e-mail.
    """

    is_mod: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="IsMod"),
        pydantic.Field(alias="IsMod", description="Moderates a community."),
    ] = None
    """
    Moderates a community.
    """

    is_suspended: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="IsSuspended"),
        pydantic.Field(alias="IsSuspended", description="Present and `true` for suspended accounts."),
    ] = None
    """
    Present and `true` for suspended accounts.
    """

    profile_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ProfileUrl"),
        pydantic.Field(alias="ProfileUrl", description="Profile link."),
    ] = None
    """
    Profile link.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
