# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class SteamExtraData(UncheckedBaseModel):
    username: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Username"),
        pydantic.Field(alias="Username", description="Steam username."),
    ] = None
    """
    Steam username.
    """

    display_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="DisplayName"),
        pydantic.Field(alias="DisplayName", description="Profile name."),
    ] = None
    """
    Profile name.
    """

    real_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="RealName"),
        pydantic.Field(alias="RealName", description="Real name, if public."),
    ] = None
    """
    Real name, if public.
    """

    profile_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ProfileUrl"),
        pydantic.Field(alias="ProfileUrl", description="Profile link."),
    ] = None
    """
    Profile link.
    """

    avatar_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="AvatarUrl"), pydantic.Field(alias="AvatarUrl", description="Avatar.")
    ] = None
    """
    Avatar.
    """

    profile_state: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="ProfileState"),
        pydantic.Field(alias="ProfileState", description="1 when the profile is set up."),
    ] = None
    """
    1 when the profile is set up.
    """

    visibility: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="Visibility"),
        pydantic.Field(alias="Visibility", description="3 = public, 1 = private."),
    ] = None
    """
    3 = public, 1 = private.
    """

    time_created: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="TimeCreated"),
        pydantic.Field(alias="TimeCreated", description="Account creation (Unix time)."),
    ] = None
    """
    Account creation (Unix time).
    """

    last_logoff: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="LastLogoff"),
        pydantic.Field(alias="LastLogoff", description="Last sign-off (Unix time)."),
    ] = None
    """
    Last sign-off (Unix time).
    """

    country_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="CountryCode"),
        pydantic.Field(alias="CountryCode", description="Country, if public."),
    ] = None
    """
    Country, if public.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
