# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class TiktokResolverResponse(UncheckedBaseModel):
    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    `true` when resolved.
    """

    sharer: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The account that shared the link: `username`, `nickname`, `avatar`, `region`, `language`, `account_created`, `follower_count`, `following_count`, `heart_count`, `video_count`, `bio`, `verified`, `private`. `resolved_via` is `sec_uid` for the sharer, or `video_author` when only the video's author could be identified.
    """

    share_info: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The share: `shared_from`, `share_time`, `device`, `language`, `region`, `account_created`.
    """

    video: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The video: `full_url`, `video_id`, `video_created`, `type`, `author_username`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
