# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .twitch_extra_data import TwitchExtraData


class TwitchResponse(UncheckedBaseModel):
    """
    `taken` is `true` when the account exists. `ExtraData` holds what the profile shows publicly; a field the profile does not have is left out. When the lookup could not be completed, `taken` is `false` and `error` says why (for example `rate_limited`, try again later).
    """

    taken: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether an account with this username exists.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Present only when the lookup could not be completed.
    """

    extra_data: typing_extensions.Annotated[
        typing.Optional[TwitchExtraData], FieldMetadata(alias="ExtraData"), pydantic.Field(alias="ExtraData")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
