# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class TwitterProfile(UncheckedBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Account ID.
    """

    username: typing.Optional[str] = pydantic.Field(default=None)
    """
    Handle.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name.
    """

    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    Account creation.
    """

    followers: typing.Optional[float] = pydantic.Field(default=None)
    """
    Followers.
    """

    following: typing.Optional[float] = pydantic.Field(default=None)
    """
    Following.
    """

    tweets_count: typing.Optional[float] = pydantic.Field(default=None)
    """
    Posts.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Bio.
    """

    profile_image: typing.Optional[str] = pydantic.Field(default=None)
    """
    Profile picture.
    """

    banner_image: typing.Optional[str] = pydantic.Field(default=None)
    """
    Banner.
    """

    verified: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Verified.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
