# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .twitter_profile import TwitterProfile


class TwitterResponse(UncheckedBaseModel):
    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    `success`.
    """

    profile: typing.Optional[TwitterProfile] = None
    recent_tweets_scraped: typing.Optional[float] = pydantic.Field(default=None)
    """
    How many recent posts the summary is based on.
    """

    ai_analysis: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The automated summary (interests, language, likely region, tone, activity pattern, authenticity estimate). Empty when no summary could be made.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
