# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class TwitchExtraData(UncheckedBaseModel):
    username: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Username"),
        pydantic.Field(alias="Username", description="Login name."),
    ] = None
    """
    Login name.
    """

    display_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="DisplayName"),
        pydantic.Field(alias="DisplayName", description="Display name."),
    ] = None
    """
    Display name.
    """

    user_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="UserID"),
        pydantic.Field(alias="UserID", description="Twitch user ID."),
    ] = None
    """
    Twitch user ID.
    """

    description: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Description"),
        pydantic.Field(alias="Description", description="Bio."),
    ] = None
    """
    Bio.
    """

    profile_pic_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ProfilePicUrl"),
        pydantic.Field(alias="ProfilePicUrl", description="Profile picture."),
    ] = None
    """
    Profile picture.
    """

    followers: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="Followers"),
        pydantic.Field(alias="Followers", description="Followers."),
    ] = None
    """
    Followers.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="CreatedAt"),
        pydantic.Field(alias="CreatedAt", description="Account creation."),
    ] = None
    """
    Account creation.
    """

    broadcaster_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="BroadcasterType"),
        pydantic.Field(alias="BroadcasterType", description="`partner`, `affiliate` or empty."),
    ] = None
    """
    `partner`, `affiliate` or empty.
    """

    banned: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="Banned"),
        pydantic.Field(alias="Banned", description="Whether the account is suspended (`BanReason` then says why)."),
    ] = None
    """
    Whether the account is suspended (`BanReason` then says why).
    """

    is_partner: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="IsPartner"),
        pydantic.Field(alias="IsPartner", description="Twitch partner."),
    ] = None
    """
    Twitch partner.
    """

    is_affiliate: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="IsAffiliate"),
        pydantic.Field(alias="IsAffiliate", description="Twitch affiliate."),
    ] = None
    """
    Twitch affiliate.
    """

    profile_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ProfileUrl"),
        pydantic.Field(alias="ProfileUrl", description="Channel link."),
    ] = None
    """
    Channel link.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
