# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .usage_meta_lookups_left import UsageMetaLookupsLeft


class UsageMeta(UncheckedBaseModel):
    """
    Your usage after this request.
    """

    plan: typing.Optional[str] = pydantic.Field(default=None)
    """
    Plan id.
    """

    lookups_left: typing.Optional[UsageMetaLookupsLeft] = pydantic.Field(default=None)
    """
    Lookups left today, `unlimited` on Max, or `charging` when the allowance is used up and the lookup was charged to your balance.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
