# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class UserAccountInfo(UncheckedBaseModel):
    username: typing.Optional[str] = pydantic.Field(default=None)
    """
    Username.
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    E-mail address of the account.
    """

    plan: typing.Optional[str] = pydantic.Field(default=None)
    """
    Current plan, e.g. `Researcher`, `Investigator`, `Max`.
    """

    plan_expires: typing.Optional[str] = pydantic.Field(default=None)
    """
    When the plan ends (ISO 8601), `Lifetime`, or `N/A`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
