# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class UserUsage(UncheckedBaseModel):
    request_limit_daily: typing.Optional[float] = pydantic.Field(default=None)
    """
    Lookups per day on this plan (Max: unlimited, shown as a very large number).
    """

    requests_remaining_today: typing.Optional[float] = pydantic.Field(default=None)
    """
    Lookups left today. Resets at 00:00 UTC.
    """

    api_access: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the plan includes API access.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
