# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class XboxExtraData(UncheckedBaseModel):
    gamertag: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="Gamertag"), pydantic.Field(alias="Gamertag", description="Gamertag.")
    ] = None
    """
    Gamertag.
    """

    xuid: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="XUID"), pydantic.Field(alias="XUID", description="Xbox user ID.")
    ] = None
    """
    Xbox user ID.
    """

    profile_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ProfileUrl"),
        pydantic.Field(alias="ProfileUrl", description="Profile link."),
    ] = None
    """
    Profile link.
    """

    avatar_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="AvatarUrl"),
        pydantic.Field(alias="AvatarUrl", description="Gamer picture."),
    ] = None
    """
    Gamer picture.
    """

    gamer_score: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="GamerScore"),
        pydantic.Field(alias="GamerScore", description="Gamerscore."),
    ] = None
    """
    Gamerscore.
    """

    account_tier: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="AccountTier"),
        pydantic.Field(alias="AccountTier", description="Account tier."),
    ] = None
    """
    Account tier.
    """

    bio: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="Bio"), pydantic.Field(alias="Bio", description="Bio.")
    ] = None
    """
    Bio.
    """

    location: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Location"),
        pydantic.Field(alias="Location", description="Location, if set."),
    ] = None
    """
    Location, if set.
    """

    tenure: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Tenure"),
        pydantic.Field(alias="Tenure", description="Years of membership."),
    ] = None
    """
    Years of membership.
    """

    is_verified: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="IsVerified"),
        pydantic.Field(alias="IsVerified", description="Verified account."),
    ] = None
    """
    Verified account.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
