# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.dns_resolver_response import DnsResolverResponse
from .raw_client import AsyncRawDnsClient, RawDnsClient


class DnsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDnsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDnsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDnsClient
        """
        return self._raw_client

    def resolve(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> DnsResolverResponse:
        """
        Resolves one or more hostnames to their IP addresses.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/dns-resolver

        Parameters
        ----------
        query : str
            A hostname, or several separated by commas.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DnsResolverResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.dns.resolve(
            query="example.com,osintcat.net",
        )
        """
        _response = self._raw_client.resolve(query=query, request_options=request_options)
        return _response.data


class AsyncDnsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDnsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDnsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDnsClient
        """
        return self._raw_client

    async def resolve(
        self, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DnsResolverResponse:
        """
        Resolves one or more hostnames to their IP addresses.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/dns-resolver

        Parameters
        ----------
        query : str
            A hostname, or several separated by commas.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DnsResolverResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.dns.resolve(
                query="example.com,osintcat.net",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resolve(query=query, request_options=request_options)
        return _response.data
