# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.twitch_response import TwitchResponse
from .raw_client import AsyncRawTwitchClient, RawTwitchClient


class TwitchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTwitchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTwitchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTwitchClient
        """
        return self._raw_client

    def profile(self, *, username: str, request_options: typing.Optional[RequestOptions] = None) -> TwitchResponse:
        """
        Look up a Twitch account by its username and get the public profile.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Missing username parameter`: No `username` given.

        Docs: https://docs.osintcat.net/api-reference/endpoint/twitch

        Parameters
        ----------
        username : str
            The Twitch username.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TwitchResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.twitch.profile(
            username="xqc",
        )
        """
        _response = self._raw_client.profile(username=username, request_options=request_options)
        return _response.data


class AsyncTwitchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTwitchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTwitchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTwitchClient
        """
        return self._raw_client

    async def profile(
        self, *, username: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TwitchResponse:
        """
        Look up a Twitch account by its username and get the public profile.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `Missing username parameter`: No `username` given.

        Docs: https://docs.osintcat.net/api-reference/endpoint/twitch

        Parameters
        ----------
        username : str
            The Twitch username.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TwitchResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.twitch.profile(
                username="xqc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.profile(username=username, request_options=request_options)
        return _response.data
