# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.twitter_response import TwitterResponse
from .raw_client import AsyncRawXClient, RawXClient


class XClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawXClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawXClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawXClient
        """
        return self._raw_client

    def profile(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> TwitterResponse:
        """
        Returns the public profile of an X (Twitter) account and an automated, best-effort summary of its recent public posts (topics, language, tone, posting pattern). Treat the summary as unverified.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 404 `User '...' not found on X (Twitter).`: No account with that username. Not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/twitter

        Parameters
        ----------
        query : str
            The X username, with or without `@`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TwitterResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.x.profile(
            query="jack",
        )
        """
        _response = self._raw_client.profile(query=query, request_options=request_options)
        return _response.data


class AsyncXClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawXClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawXClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawXClient
        """
        return self._raw_client

    async def profile(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> TwitterResponse:
        """
        Returns the public profile of an X (Twitter) account and an automated, best-effort summary of its recent public posts (topics, language, tone, posting pattern). Treat the summary as unverified.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 404 `User '...' not found on X (Twitter).`: No account with that username. Not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/twitter

        Parameters
        ----------
        query : str
            The X username, with or without `@`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TwitterResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.x.profile(
                query="jack",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.profile(query=query, request_options=request_options)
        return _response.data
