# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.ip_response import IpResponse
from .raw_client import AsyncRawIpClient, RawIpClient


class IpClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawIpClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawIpClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawIpClient
        """
        return self._raw_client

    def lookup(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> IpResponse:
        """
        Returns what is known about an IP address: open ports and services seen on it, hostnames, and its location and network.

        Results for the same address may come from a cache for up to two days.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/ip

        Parameters
        ----------
        query : str
            An IPv4 or IPv6 address.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IpResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.ip.lookup(
            query="8.8.8.8",
        )
        """
        _response = self._raw_client.lookup(query=query, request_options=request_options)
        return _response.data


class AsyncIpClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawIpClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawIpClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawIpClient
        """
        return self._raw_client

    async def lookup(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> IpResponse:
        """
        Returns what is known about an IP address: open ports and services seen on it, hostnames, and its location and network.

        Results for the same address may come from a cache for up to two days.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/ip

        Parameters
        ----------
        query : str
            An IPv4 or IPv6 address.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IpResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.ip.lookup(
                query="8.8.8.8",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.lookup(query=query, request_options=request_options)
        return _response.data
