# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import os
import typing

import httpx
from .core.api_error import ApiError
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import OsintCatEnvironment

if typing.TYPE_CHECKING:
    from .account.client import AccountClient, AsyncAccountClient
    from .breach.client import AsyncBreachClient, BreachClient
    from .chess.client import AsyncChessClient, ChessClient
    from .chile.client import AsyncChileClient, ChileClient
    from .dns.client import AsyncDnsClient, DnsClient
    from .email.client import AsyncEmailClient, EmailClient
    from .github.client import AsyncGithubClient, GithubClient
    from .instagram.client import AsyncInstagramClient, InstagramClient
    from .ip.client import AsyncIpClient, IpClient
    from .minecraft.client import AsyncMinecraftClient, MinecraftClient
    from .phone.client import AsyncPhoneClient, PhoneClient
    from .reddit.client import AsyncRedditClient, RedditClient
    from .steam.client import AsyncSteamClient, SteamClient
    from .tiktok.client import AsyncTiktokClient, TiktokClient
    from .twitch.client import AsyncTwitchClient, TwitchClient
    from .vin.client import AsyncVinClient, VinClient
    from .x.client import AsyncXClient, XClient
    from .xbox.client import AsyncXboxClient, XboxClient


class OsintCat:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : OsintCatEnvironment
        The environment to use for requests from the client. from .environment import OsintCatEnvironment



        Defaults to OsintCatEnvironment.PRODUCTION



    api_key : typing.Optional[str]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 0. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from osintcat import OsintCat

    client = OsintCat(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: OsintCatEnvironment = OsintCatEnvironment.PRODUCTION,
        api_key: typing.Optional[str] = os.getenv("OSINTCAT_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 0
        if api_key is None:
            raise ApiError(
                body="The client must be instantiated be either passing in api_key or setting OSINTCAT_API_KEY"
            )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._account: typing.Optional[AccountClient] = None
        self._breach: typing.Optional[BreachClient] = None
        self._email: typing.Optional[EmailClient] = None
        self._phone: typing.Optional[PhoneClient] = None
        self._ip: typing.Optional[IpClient] = None
        self._dns: typing.Optional[DnsClient] = None
        self._minecraft: typing.Optional[MinecraftClient] = None
        self._steam: typing.Optional[SteamClient] = None
        self._xbox: typing.Optional[XboxClient] = None
        self._twitch: typing.Optional[TwitchClient] = None
        self._chess: typing.Optional[ChessClient] = None
        self._github: typing.Optional[GithubClient] = None
        self._reddit: typing.Optional[RedditClient] = None
        self._x: typing.Optional[XClient] = None
        self._tiktok: typing.Optional[TiktokClient] = None
        self._instagram: typing.Optional[InstagramClient] = None
        self._vin: typing.Optional[VinClient] = None
        self._chile: typing.Optional[ChileClient] = None

    @property
    def account(self):
        if self._account is None:
            from .account.client import AccountClient  # noqa: E402

            self._account = AccountClient(client_wrapper=self._client_wrapper)
        return self._account

    @property
    def breach(self):
        if self._breach is None:
            from .breach.client import BreachClient  # noqa: E402

            self._breach = BreachClient(client_wrapper=self._client_wrapper)
        return self._breach

    @property
    def email(self):
        if self._email is None:
            from .email.client import EmailClient  # noqa: E402

            self._email = EmailClient(client_wrapper=self._client_wrapper)
        return self._email

    @property
    def phone(self):
        if self._phone is None:
            from .phone.client import PhoneClient  # noqa: E402

            self._phone = PhoneClient(client_wrapper=self._client_wrapper)
        return self._phone

    @property
    def ip(self):
        if self._ip is None:
            from .ip.client import IpClient  # noqa: E402

            self._ip = IpClient(client_wrapper=self._client_wrapper)
        return self._ip

    @property
    def dns(self):
        if self._dns is None:
            from .dns.client import DnsClient  # noqa: E402

            self._dns = DnsClient(client_wrapper=self._client_wrapper)
        return self._dns

    @property
    def minecraft(self):
        if self._minecraft is None:
            from .minecraft.client import MinecraftClient  # noqa: E402

            self._minecraft = MinecraftClient(client_wrapper=self._client_wrapper)
        return self._minecraft

    @property
    def steam(self):
        if self._steam is None:
            from .steam.client import SteamClient  # noqa: E402

            self._steam = SteamClient(client_wrapper=self._client_wrapper)
        return self._steam

    @property
    def xbox(self):
        if self._xbox is None:
            from .xbox.client import XboxClient  # noqa: E402

            self._xbox = XboxClient(client_wrapper=self._client_wrapper)
        return self._xbox

    @property
    def twitch(self):
        if self._twitch is None:
            from .twitch.client import TwitchClient  # noqa: E402

            self._twitch = TwitchClient(client_wrapper=self._client_wrapper)
        return self._twitch

    @property
    def chess(self):
        if self._chess is None:
            from .chess.client import ChessClient  # noqa: E402

            self._chess = ChessClient(client_wrapper=self._client_wrapper)
        return self._chess

    @property
    def github(self):
        if self._github is None:
            from .github.client import GithubClient  # noqa: E402

            self._github = GithubClient(client_wrapper=self._client_wrapper)
        return self._github

    @property
    def reddit(self):
        if self._reddit is None:
            from .reddit.client import RedditClient  # noqa: E402

            self._reddit = RedditClient(client_wrapper=self._client_wrapper)
        return self._reddit

    @property
    def x(self):
        if self._x is None:
            from .x.client import XClient  # noqa: E402

            self._x = XClient(client_wrapper=self._client_wrapper)
        return self._x

    @property
    def tiktok(self):
        if self._tiktok is None:
            from .tiktok.client import TiktokClient  # noqa: E402

            self._tiktok = TiktokClient(client_wrapper=self._client_wrapper)
        return self._tiktok

    @property
    def instagram(self):
        if self._instagram is None:
            from .instagram.client import InstagramClient  # noqa: E402

            self._instagram = InstagramClient(client_wrapper=self._client_wrapper)
        return self._instagram

    @property
    def vin(self):
        if self._vin is None:
            from .vin.client import VinClient  # noqa: E402

            self._vin = VinClient(client_wrapper=self._client_wrapper)
        return self._vin

    @property
    def chile(self):
        if self._chile is None:
            from .chile.client import ChileClient  # noqa: E402

            self._chile = ChileClient(client_wrapper=self._client_wrapper)
        return self._chile


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncOsintCat:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : OsintCatEnvironment
        The environment to use for requests from the client. from .environment import OsintCatEnvironment



        Defaults to OsintCatEnvironment.PRODUCTION



    api_key : typing.Optional[str]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 0. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from osintcat import AsyncOsintCat

    client = AsyncOsintCat(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: OsintCatEnvironment = OsintCatEnvironment.PRODUCTION,
        api_key: typing.Optional[str] = os.getenv("OSINTCAT_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 0
        if api_key is None:
            raise ApiError(
                body="The client must be instantiated be either passing in api_key or setting OSINTCAT_API_KEY"
            )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._account: typing.Optional[AsyncAccountClient] = None
        self._breach: typing.Optional[AsyncBreachClient] = None
        self._email: typing.Optional[AsyncEmailClient] = None
        self._phone: typing.Optional[AsyncPhoneClient] = None
        self._ip: typing.Optional[AsyncIpClient] = None
        self._dns: typing.Optional[AsyncDnsClient] = None
        self._minecraft: typing.Optional[AsyncMinecraftClient] = None
        self._steam: typing.Optional[AsyncSteamClient] = None
        self._xbox: typing.Optional[AsyncXboxClient] = None
        self._twitch: typing.Optional[AsyncTwitchClient] = None
        self._chess: typing.Optional[AsyncChessClient] = None
        self._github: typing.Optional[AsyncGithubClient] = None
        self._reddit: typing.Optional[AsyncRedditClient] = None
        self._x: typing.Optional[AsyncXClient] = None
        self._tiktok: typing.Optional[AsyncTiktokClient] = None
        self._instagram: typing.Optional[AsyncInstagramClient] = None
        self._vin: typing.Optional[AsyncVinClient] = None
        self._chile: typing.Optional[AsyncChileClient] = None

    @property
    def account(self):
        if self._account is None:
            from .account.client import AsyncAccountClient  # noqa: E402

            self._account = AsyncAccountClient(client_wrapper=self._client_wrapper)
        return self._account

    @property
    def breach(self):
        if self._breach is None:
            from .breach.client import AsyncBreachClient  # noqa: E402

            self._breach = AsyncBreachClient(client_wrapper=self._client_wrapper)
        return self._breach

    @property
    def email(self):
        if self._email is None:
            from .email.client import AsyncEmailClient  # noqa: E402

            self._email = AsyncEmailClient(client_wrapper=self._client_wrapper)
        return self._email

    @property
    def phone(self):
        if self._phone is None:
            from .phone.client import AsyncPhoneClient  # noqa: E402

            self._phone = AsyncPhoneClient(client_wrapper=self._client_wrapper)
        return self._phone

    @property
    def ip(self):
        if self._ip is None:
            from .ip.client import AsyncIpClient  # noqa: E402

            self._ip = AsyncIpClient(client_wrapper=self._client_wrapper)
        return self._ip

    @property
    def dns(self):
        if self._dns is None:
            from .dns.client import AsyncDnsClient  # noqa: E402

            self._dns = AsyncDnsClient(client_wrapper=self._client_wrapper)
        return self._dns

    @property
    def minecraft(self):
        if self._minecraft is None:
            from .minecraft.client import AsyncMinecraftClient  # noqa: E402

            self._minecraft = AsyncMinecraftClient(client_wrapper=self._client_wrapper)
        return self._minecraft

    @property
    def steam(self):
        if self._steam is None:
            from .steam.client import AsyncSteamClient  # noqa: E402

            self._steam = AsyncSteamClient(client_wrapper=self._client_wrapper)
        return self._steam

    @property
    def xbox(self):
        if self._xbox is None:
            from .xbox.client import AsyncXboxClient  # noqa: E402

            self._xbox = AsyncXboxClient(client_wrapper=self._client_wrapper)
        return self._xbox

    @property
    def twitch(self):
        if self._twitch is None:
            from .twitch.client import AsyncTwitchClient  # noqa: E402

            self._twitch = AsyncTwitchClient(client_wrapper=self._client_wrapper)
        return self._twitch

    @property
    def chess(self):
        if self._chess is None:
            from .chess.client import AsyncChessClient  # noqa: E402

            self._chess = AsyncChessClient(client_wrapper=self._client_wrapper)
        return self._chess

    @property
    def github(self):
        if self._github is None:
            from .github.client import AsyncGithubClient  # noqa: E402

            self._github = AsyncGithubClient(client_wrapper=self._client_wrapper)
        return self._github

    @property
    def reddit(self):
        if self._reddit is None:
            from .reddit.client import AsyncRedditClient  # noqa: E402

            self._reddit = AsyncRedditClient(client_wrapper=self._client_wrapper)
        return self._reddit

    @property
    def x(self):
        if self._x is None:
            from .x.client import AsyncXClient  # noqa: E402

            self._x = AsyncXClient(client_wrapper=self._client_wrapper)
        return self._x

    @property
    def tiktok(self):
        if self._tiktok is None:
            from .tiktok.client import AsyncTiktokClient  # noqa: E402

            self._tiktok = AsyncTiktokClient(client_wrapper=self._client_wrapper)
        return self._tiktok

    @property
    def instagram(self):
        if self._instagram is None:
            from .instagram.client import AsyncInstagramClient  # noqa: E402

            self._instagram = AsyncInstagramClient(client_wrapper=self._client_wrapper)
        return self._instagram

    @property
    def vin(self):
        if self._vin is None:
            from .vin.client import AsyncVinClient  # noqa: E402

            self._vin = AsyncVinClient(client_wrapper=self._client_wrapper)
        return self._vin

    @property
    def chile(self):
        if self._chile is None:
            from .chile.client import AsyncChileClient  # noqa: E402

            self._chile = AsyncChileClient(client_wrapper=self._client_wrapper)
        return self._chile


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: OsintCatEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
