# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.modules_response import ModulesResponse
from ..types.user_response import UserResponse
from .raw_client import AsyncRawAccountClient, RawAccountClient


class AccountClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAccountClient
        """
        return self._raw_client

    def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> UserResponse:
        """
        Returns the account the API key belongs to: plan, plan expiry, and how many lookups are left today.

        Does not count as a lookup.

        Needs the `account:read` scope (keys with all scopes have it).

        Errors:
        - 401 `API key required`: No `X-API-KEY` header.
        - 403 `Invalid API key`: The key does not exist or was revoked.
        - 403 `insufficient_scope`: The key lacks the `account:read` scope.

        Docs: https://docs.osintcat.net/api-reference/endpoint/user

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.account.get()
        """
        _response = self._raw_client.get(request_options=request_options)
        return _response.data

    def modules(self, *, request_options: typing.Optional[RequestOptions] = None) -> ModulesResponse:
        """
        Lists every module with its current state and whether your account can use it. Use it to check access before calling a lookup: a lookup for a module your plan does not include is refused with `403 ACCESS_DENIED`.

        Does not count as a lookup.

        Needs the `osint:read` scope.

        Errors:
        - 401 `Unauthorized`: Missing or unknown key.

        Docs: https://docs.osintcat.net/api-reference/endpoint/modules

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModulesResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.account.modules()
        """
        _response = self._raw_client.modules(request_options=request_options)
        return _response.data


class AsyncAccountClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAccountClient
        """
        return self._raw_client

    async def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> UserResponse:
        """
        Returns the account the API key belongs to: plan, plan expiry, and how many lookups are left today.

        Does not count as a lookup.

        Needs the `account:read` scope (keys with all scopes have it).

        Errors:
        - 401 `API key required`: No `X-API-KEY` header.
        - 403 `Invalid API key`: The key does not exist or was revoked.
        - 403 `insufficient_scope`: The key lacks the `account:read` scope.

        Docs: https://docs.osintcat.net/api-reference/endpoint/user

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.account.get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get(request_options=request_options)
        return _response.data

    async def modules(self, *, request_options: typing.Optional[RequestOptions] = None) -> ModulesResponse:
        """
        Lists every module with its current state and whether your account can use it. Use it to check access before calling a lookup: a lookup for a module your plan does not include is refused with `403 ACCESS_DENIED`.

        Does not count as a lookup.

        Needs the `osint:read` scope.

        Errors:
        - 401 `Unauthorized`: Missing or unknown key.

        Docs: https://docs.osintcat.net/api-reference/endpoint/modules

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModulesResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.account.modules()


        asyncio.run(main())
        """
        _response = await self._raw_client.modules(request_options=request_options)
        return _response.data
