# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from ..core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.error import Error
from ..types.vin_response import VinResponse
from .types.query_vin_request_type import QueryVinRequestType
from .types.query_vin_request_units import QueryVinRequestUnits
from pydantic import ValidationError


class RawVinClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def query(
        self,
        *,
        operation: typing.Optional[QueryVinRequestType] = None,
        query: typing.Optional[str] = None,
        model_year: typing.Optional[float] = None,
        extended: typing.Optional[bool] = None,
        search_type: typing.Optional[str] = None,
        year: typing.Optional[float] = None,
        vehicle_type: typing.Optional[str] = None,
        mfr_type: typing.Optional[str] = None,
        page: typing.Optional[float] = None,
        parts_type: typing.Optional[str] = None,
        from_date: typing.Optional[str] = None,
        to_date: typing.Optional[str] = None,
        make: typing.Optional[str] = None,
        model: typing.Optional[str] = None,
        units: typing.Optional[QueryVinRequestUnits] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[VinResponse]:
        """
        Decodes vehicle identification numbers and answers catalogue questions (makes, models, manufacturers, vehicle variables). Choose what to do with `type`.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `query parameter is required`: `query` missing where the chosen type needs it.
        - 400 `Maximum 50 VINs allowed`: `batch` with more than 50 VINs.
        - 400 `Invalid query type / Invalid search_type`: Unknown `type` or `search_type`.

        Docs: https://docs.osintcat.net/api-reference/endpoint/vin

        Parameters
        ----------
        operation : typing.Optional[QueryVinRequestType]
            `decode` (default), `batch`, `wmi`, `makes`, `manufacturers`, `variables` or `canadian`.

        query : typing.Optional[str]
            The VIN (`decode`), VINs separated by new lines, up to 50 (`batch`), a WMI (`wmi`), or the make / manufacturer / variable name the chosen `search_type` needs. Not needed for `makes`+`all`, `manufacturers`+`all`/`parts`, `variables`+`list` and `canadian`.

        model_year : typing.Optional[float]
            `decode`: model year, improves accuracy.

        extended : typing.Optional[bool]
            `decode`: `true` for the extended field set.

        search_type : typing.Optional[str]
            `makes`: `all`, `manufacturer`, `vehicletype`, `models`, `vehicletypes`. `manufacturers`: `all`, `details`, `wmis`, `parts`. `variables`: `list`, `values`.

        year : typing.Optional[float]
            `makes` with `manufacturer`/`models`, and `canadian`: model year.

        vehicle_type : typing.Optional[str]
            `makes`+`models` and `manufacturers`+`wmis`: vehicle type filter.

        mfr_type : typing.Optional[str]
            `manufacturers`+`all`: manufacturer type filter.

        page : typing.Optional[float]
            `manufacturers`+`all`/`parts`: page number.

        parts_type : typing.Optional[str]
            `manufacturers`+`parts`: CFR part, default `565`.

        from_date : typing.Optional[str]
            `manufacturers`+`parts`: start date (required there).

        to_date : typing.Optional[str]
            `manufacturers`+`parts`: end date (required there).

        make : typing.Optional[str]
            `canadian`: make.

        model : typing.Optional[str]
            `canadian`: model.

        units : typing.Optional[QueryVinRequestUnits]
            `canadian`: `Metric` (default) or `US`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[VinResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/vin",
            method="GET",
            params={
                "type": operation,
                "query": query,
                "model_year": model_year,
                "extended": extended,
                "search_type": search_type,
                "year": year,
                "vehicle_type": vehicle_type,
                "mfr_type": mfr_type,
                "page": page,
                "parts_type": parts_type,
                "from_date": from_date,
                "to_date": to_date,
                "make": make,
                "model": model,
                "units": units,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VinResponse,
                    construct_type(
                        type_=VinResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        construct_type(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        construct_type(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        construct_type(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        construct_type(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawVinClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def query(
        self,
        *,
        operation: typing.Optional[QueryVinRequestType] = None,
        query: typing.Optional[str] = None,
        model_year: typing.Optional[float] = None,
        extended: typing.Optional[bool] = None,
        search_type: typing.Optional[str] = None,
        year: typing.Optional[float] = None,
        vehicle_type: typing.Optional[str] = None,
        mfr_type: typing.Optional[str] = None,
        page: typing.Optional[float] = None,
        parts_type: typing.Optional[str] = None,
        from_date: typing.Optional[str] = None,
        to_date: typing.Optional[str] = None,
        make: typing.Optional[str] = None,
        model: typing.Optional[str] = None,
        units: typing.Optional[QueryVinRequestUnits] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[VinResponse]:
        """
        Decodes vehicle identification numbers and answers catalogue questions (makes, models, manufacturers, vehicle variables). Choose what to do with `type`.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 400 `query parameter is required`: `query` missing where the chosen type needs it.
        - 400 `Maximum 50 VINs allowed`: `batch` with more than 50 VINs.
        - 400 `Invalid query type / Invalid search_type`: Unknown `type` or `search_type`.

        Docs: https://docs.osintcat.net/api-reference/endpoint/vin

        Parameters
        ----------
        operation : typing.Optional[QueryVinRequestType]
            `decode` (default), `batch`, `wmi`, `makes`, `manufacturers`, `variables` or `canadian`.

        query : typing.Optional[str]
            The VIN (`decode`), VINs separated by new lines, up to 50 (`batch`), a WMI (`wmi`), or the make / manufacturer / variable name the chosen `search_type` needs. Not needed for `makes`+`all`, `manufacturers`+`all`/`parts`, `variables`+`list` and `canadian`.

        model_year : typing.Optional[float]
            `decode`: model year, improves accuracy.

        extended : typing.Optional[bool]
            `decode`: `true` for the extended field set.

        search_type : typing.Optional[str]
            `makes`: `all`, `manufacturer`, `vehicletype`, `models`, `vehicletypes`. `manufacturers`: `all`, `details`, `wmis`, `parts`. `variables`: `list`, `values`.

        year : typing.Optional[float]
            `makes` with `manufacturer`/`models`, and `canadian`: model year.

        vehicle_type : typing.Optional[str]
            `makes`+`models` and `manufacturers`+`wmis`: vehicle type filter.

        mfr_type : typing.Optional[str]
            `manufacturers`+`all`: manufacturer type filter.

        page : typing.Optional[float]
            `manufacturers`+`all`/`parts`: page number.

        parts_type : typing.Optional[str]
            `manufacturers`+`parts`: CFR part, default `565`.

        from_date : typing.Optional[str]
            `manufacturers`+`parts`: start date (required there).

        to_date : typing.Optional[str]
            `manufacturers`+`parts`: end date (required there).

        make : typing.Optional[str]
            `canadian`: make.

        model : typing.Optional[str]
            `canadian`: model.

        units : typing.Optional[QueryVinRequestUnits]
            `canadian`: `Metric` (default) or `US`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[VinResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/vin",
            method="GET",
            params={
                "type": operation,
                "query": query,
                "model_year": model_year,
                "extended": extended,
                "search_type": search_type,
                "year": year,
                "vehicle_type": vehicle_type,
                "mfr_type": mfr_type,
                "page": page,
                "parts_type": parts_type,
                "from_date": from_date,
                "to_date": to_date,
                "make": make,
                "model": model,
                "units": units,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VinResponse,
                    construct_type(
                        type_=VinResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        construct_type(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        construct_type(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        construct_type(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        construct_type(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
