# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.breach_response import BreachResponse
from ..types.database_search_response import DatabaseSearchResponse
from ..types.domain_response import DomainResponse
from .raw_client import AsyncRawBreachClient, RawBreachClient
from .types.database_search_breach_request_type import DatabaseSearchBreachRequestType


class BreachClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBreachClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBreachClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBreachClient
        """
        return self._raw_client

    def search(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> BreachResponse:
        """
        Searches the breach indexes (including Snusbase, LeakCheck and IntelX) for a value and returns every matching record. The search is case-insensitive.

        Results for the same query may come from a cache for up to two days.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/breach

        Parameters
        ----------
        query : str
            What to search for: an e-mail address, username, domain, phone number, IP address, name or password.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BreachResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.breach.search(
            query="user@example.com",
        )
        """
        _response = self._raw_client.search(query=query, request_options=request_options)
        return _response.data

    def database_search(
        self,
        *,
        query: str,
        query_type: typing.Optional[DatabaseSearchBreachRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DatabaseSearchResponse:
        """
        Searches stealer-log and combo-list collections for an e-mail address or a domain.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 502 `Upstream error`: The search backend answered with an error. Not charged.
        - 504 `timeout error`: The search backend did not answer in time. Not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/database-search

        Parameters
        ----------
        query : str
            The e-mail address or domain.

        query_type : typing.Optional[DatabaseSearchBreachRequestType]
            `email` or `domain`. Detected from `query` when left out.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DatabaseSearchResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.breach.database_search(
            query="user@example.com",
        )
        """
        _response = self._raw_client.database_search(
            query=query, query_type=query_type, request_options=request_options
        )
        return _response.data

    def domain(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> DomainResponse:
        """
        Returns breach records whose e-mail addresses or URLs belong to a domain.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests are refused with `429 LIMIT_REACHED` until it resets at 00:00 UTC.

        Errors:
        - 404 `No results found`: Nothing was found for the domain.
        - 502 `Upstream error`: The search could not be completed; the response carries an `error_id`.

        Docs: https://docs.osintcat.net/api-reference/endpoint/domain

        Parameters
        ----------
        query : str
            The domain, e.g. `example.com`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DomainResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.breach.domain(
            query="example.com",
        )
        """
        _response = self._raw_client.domain(query=query, request_options=request_options)
        return _response.data


class AsyncBreachClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBreachClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBreachClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBreachClient
        """
        return self._raw_client

    async def search(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> BreachResponse:
        """
        Searches the breach indexes (including Snusbase, LeakCheck and IntelX) for a value and returns every matching record. The search is case-insensitive.

        Results for the same query may come from a cache for up to two days.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/breach

        Parameters
        ----------
        query : str
            What to search for: an e-mail address, username, domain, phone number, IP address, name or password.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BreachResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.breach.search(
                query="user@example.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search(query=query, request_options=request_options)
        return _response.data

    async def database_search(
        self,
        *,
        query: str,
        query_type: typing.Optional[DatabaseSearchBreachRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DatabaseSearchResponse:
        """
        Searches stealer-log and combo-list collections for an e-mail address or a domain.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Errors:
        - 502 `Upstream error`: The search backend answered with an error. Not charged.
        - 504 `timeout error`: The search backend did not answer in time. Not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/database-search

        Parameters
        ----------
        query : str
            The e-mail address or domain.

        query_type : typing.Optional[DatabaseSearchBreachRequestType]
            `email` or `domain`. Detected from `query` when left out.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DatabaseSearchResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.breach.database_search(
                query="user@example.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.database_search(
            query=query, query_type=query_type, request_options=request_options
        )
        return _response.data

    async def domain(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> DomainResponse:
        """
        Returns breach records whose e-mail addresses or URLs belong to a domain.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests are refused with `429 LIMIT_REACHED` until it resets at 00:00 UTC.

        Errors:
        - 404 `No results found`: Nothing was found for the domain.
        - 502 `Upstream error`: The search could not be completed; the response carries an `error_id`.

        Docs: https://docs.osintcat.net/api-reference/endpoint/domain

        Parameters
        ----------
        query : str
            The domain, e.g. `example.com`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DomainResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.breach.domain(
                query="example.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.domain(query=query, request_options=request_options)
        return _response.data
