# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chess_response import ChessResponse
from .raw_client import AsyncRawChessClient, RawChessClient


class ChessClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChessClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChessClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChessClient
        """
        return self._raw_client

    def lookup(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> ChessResponse:
        """
        Returns the Chess.com profile of a player (ratings, clubs) and any records about the account found in the Chess.com leak.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/chess

        Parameters
        ----------
        query : str
            A Chess.com username or an e-mail address.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChessResponse
            OK

        Examples
        --------
        from osintcat import OsintCat

        client = OsintCat(
            api_key="YOUR_API_KEY",
        )
        client.chess.lookup(
            query="hikaru",
        )
        """
        _response = self._raw_client.lookup(query=query, request_options=request_options)
        return _response.data


class AsyncChessClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChessClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChessClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChessClient
        """
        return self._raw_client

    async def lookup(self, *, query: str, request_options: typing.Optional[RequestOptions] = None) -> ChessResponse:
        """
        Returns the Chess.com profile of a player (ratings, clubs) and any records about the account found in the Chess.com leak.

        Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.

        Docs: https://docs.osintcat.net/api-reference/endpoint/chess

        Parameters
        ----------
        query : str
            A Chess.com username or an e-mail address.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChessResponse
            OK

        Examples
        --------
        import asyncio

        from osintcat import AsyncOsintCat

        client = AsyncOsintCat(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chess.lookup(
                query="hikaru",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.lookup(query=query, request_options=request_options)
        return _response.data
